# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()

arr1d = np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()

arr2d = np.array([[4,5,6], [7,8,9]])
# Create a 3-dimensional Numpy array using np.array()

arr3d = np.array([[[1,2,3],[1,1,1],[2,2,2]],[[4,4,4,],[5,5,5],[6,6,6]],[[1,1,1],[2,2,2],[8,8,8]]])

arr3d, arr1d, arr2d


(array([[[1, 2, 3],
         [1, 1, 1],
         [2, 2, 2]],
 
        [[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [8, 8, 8]]]),
 array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1d.shape, arr1d.ndim, arr1d.dtype, arr1d.size, type(arr1d)


((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2d.size, arr2d.shape, arr2d.ndim, arr2d.dtype, type(arr2d)

(6, (2, 3), 2, dtype('int64'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr3d.shape, arr3d.ndim, arr3d.dtype, arr3d.size, type(arr3d)

((3, 3, 3), 3, dtype('int64'), 27, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df_arr = pd.DataFrame(arr2d, index=['a','b'], columns=['cat', 'dog', 'Otter'])
df_arr

cat  dog  Otter
a    4    5      6
b    7    8      9

In [7]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes_arr = np.zeros((7,2,3))
zeroes_arr


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
array_aran = np.arange(0,100,3)
array_aran


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_rand = np.random.randint(0,10, size=(7,2))
array_rand

array([[9, 5],
       [6, 5],
       [1, 0],
       [5, 6],
       [1, 6],
       [0, 4],
       [6, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_randf = np.random.random(size=(3,5))
array_randf


array([[0.31369125, 0.9469934 , 0.13322862, 0.71583362, 0.28822673],
       [0.54083182, 0.30916491, 0.23951903, 0.89262208, 0.13263527],
       [0.07104044, 0.85468401, 0.85153   , 0.82535455, 0.55792262]])

In [12]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
array_rands = np.random.randint(0,10, size=(4,6))
array_rands

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_randu = np.random.randint(1,10, size=(3,7))


# Find the unique numbers in the array you just created
arr_randu, np.unique(arr_randu)


(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [14]:
# Find the 0'th index of the latest array you created
arr_randu[0], arr_randu[0,0]


(array([9, 1, 3, 7, 4, 9, 3]), 9)

In [15]:
# Get the first 2 rows of latest array you created
arr_randu[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
arr_randu[:2,:2]


array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_randla = np.random.randint(10, size=(3,5))
ones_la = np.ones((3,5))
arr_randla, ones_la

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
# Add the two arrays together
arr_randla + ones_la

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones_lad = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
arr_randla + ones_lad

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# reshaping
ones_lad.reshape((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create another array of ones of shape (3, 5)


In [ ]:
# Subtract the new array of ones from the other most recent array
arr_randla - ones_la

array([[ 0.,  3.,  6.,  8.,  7.],
       [ 7., -1.,  7.,  5.,  7.],
       [ 6., -1.,  6.,  6.,  1.]])

In [ ]:
# Multiply the ones array with the latest array
arr_randla * ones_la

array([[1., 4., 7., 9., 8.],
       [8., 0., 8., 6., 8.],
       [7., 0., 7., 7., 2.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
arr_randla ** 2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]])

In [ ]:
# Do the same thing with np.square()
np.square(arr_randla)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(arr_randla), arr_randla.mean()

(5.466666666666667, 5.466666666666667)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(arr_randla)

9

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(arr_randla)

0

In [ ]:
# Find the standard deviation of the latest array
np.std(arr_randla)

3.0739045022396008

In [ ]:
# Find the variance of the latest array
np.var(arr_randla)

9.448888888888888

In [ ]:
# Reshape the latest array to (3, 5, 1)
np.reshape(arr_randla, (3,5,1))

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [ ]:
# Transpose the latest array
arr_randla.T, arr_randla.shape, arr_randla.T.shape

(array([[1, 8, 7],
        [4, 0, 0],
        [7, 8, 7],
        [9, 6, 7],
        [8, 8, 2]]),
 (3, 5),
 (5, 3))

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arrp1 = np.random.randint(0,10, size=(3,3))
arrp2 = np.random.randint(0,10, size=(3,2))

arrp1, arrp2


(array([[0, 7, 2],
        [2, 0, 4],
        [9, 6, 9]]),
 array([[8, 6],
        [8, 7],
        [1, 0]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
arrp1.dot(arrp2)

array([[ 58,  49],
       [ 20,  12],
       [129,  96]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arrp3 = np.random.randint(0,10, size=(4,3))
arrp4 = np.random.randint(0,10, size=(4,3))

arrp3, arrp4


(array([[6, 6, 7],
        [4, 2, 7],
        [5, 2, 0],
        [2, 4, 2]]),
 array([[0, 4, 9],
        [6, 6, 8],
        [9, 9, 2],
        [6, 0, 3]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
arrp3.dot(arrp4)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arrp3.dot(arrp4.T)

array([[ 87, 128, 122,  57],
       [ 71,  92,  68,  45],
       [  8,  42,  63,  30],
       [ 34,  52,  58,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [ ]:
# Compare the two arrays with '>'
arrp3 > arrp4

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
arrp3 >= arrp4

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [ ]:
# Find which elements of the first array are greater than 7
arrp3 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
arrp3 == arrp4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order

np.sort(arrp3)


array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(arrp3), arrp3

(array([[0, 1, 2],
        [1, 0, 2],
        [2, 1, 0],
        [0, 2, 1]]),
 array([[6, 6, 7],
        [4, 2, 7],
        [5, 2, 0],
        [2, 4, 2]]))

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.max(arrp3), np.argmax(arrp3), np.argmax(arrp3, axis=0), np.argmax(arrp3, axis=1)

(7, 2, array([0, 0, 0]), array([2, 2, 0, 1]))

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arrp3)

8

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arrp3, axis=1)


array([2, 2, 0, 1])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arrp3, axis=0)

array([3, 1, 2])

In [ ]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.